-- ============================================
-- MediasAPI - Baseline Schema Migration
-- Version: 1.0
-- Description: Initial database schema creation
-- Author: Generated by Flyway Migration
-- Date: 2025-11-28
-- ============================================

-- ============================================
-- Table: users
-- Description: Stores user information and authentication
-- ============================================
CREATE TABLE IF NOT EXISTS users (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50),
    PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- Table: course
-- Description: Stores academic courses with custom grading formulas
-- ============================================
CREATE TABLE IF NOT EXISTS course (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    average_method TEXT NOT NULL,
    cut_off_grade DOUBLE NOT NULL DEFAULT 6.0,
    PRIMARY KEY (id),
    CONSTRAINT uk_course_name_user UNIQUE (name, user_id),
    CONSTRAINT fk_course_user FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- Table: projection
-- Description: Stores grade projections for courses
-- ============================================
CREATE TABLE IF NOT EXISTS projection (
    id BIGINT NOT NULL AUTO_INCREMENT,
    course_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    final_grade DOUBLE NOT NULL DEFAULT 0.0,
    PRIMARY KEY (id),
    CONSTRAINT uk_projection_name_course UNIQUE (name, course_id),
    CONSTRAINT fk_projection_course FOREIGN KEY (course_id)
        REFERENCES course(id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- Table: assessment
-- Description: Stores individual assessments within projections
-- ============================================
CREATE TABLE IF NOT EXISTS assessment (
    id BIGINT NOT NULL AUTO_INCREMENT,
    projection_id BIGINT NOT NULL,
    identifier VARCHAR(255) NOT NULL,
    grade DOUBLE NOT NULL DEFAULT 0.0,
    max_value DOUBLE NOT NULL DEFAULT 10.0,
    required_grade DOUBLE NOT NULL DEFAULT 0.0,
    fixed BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id),
    CONSTRAINT uk_assessment_identifier_projection UNIQUE (identifier, projection_id),
    CONSTRAINT fk_assessment_projection FOREIGN KEY (projection_id)
        REFERENCES projection(id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- Indexes for Performance Optimization
-- ============================================

-- Index on foreign keys for faster joins
CREATE INDEX idx_course_user_id ON course(user_id);
CREATE INDEX idx_projection_course_id ON projection(course_id);
CREATE INDEX idx_assessment_projection_id ON assessment(projection_id);

-- Index on email for authentication queries
CREATE INDEX idx_users_email ON users(email);

-- ============================================
-- Comments for Documentation
-- ============================================

-- Users table stores authentication and profile information
-- Role is stored as ENUM string: 'ADMIN' or 'USER'

-- Course table stores the grading formula in average_method
-- The formula is parsed using regex and evaluated with RPN (Reverse Polish Notation)

-- Projection table allows multiple scenarios per course
-- Each projection has its own set of assessments

-- Assessment table stores individual grades
-- The 'fixed' flag indicates if the grade is final or can be changed
-- required_grade is calculated automatically based on cut_off_grade
